backend:
  name: git-gateway
  branch: main  # Altere para o nome do seu branch principal, ex: 'main' ou 'master'

media_folder: "static/uploads"  # Pasta onde as imagens serão salvas
public_folder: "/uploads"       # Caminho público para acessar as imagens

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Corpo", name: "body", widget: "markdown" }
